#!/usr/bin/env python3
"""Write a non-technical brief alongside the technical action sheets.

Does **not** modify UNIFIED_ACTION_SHEET.csv, SCAN_BRIEFING.html, or
BLAST_RADIUS_LEADERSHIP.md — those stay generated by export_bundle_action_sheet.py.

Output: docs/sample_reports/actionable/PLAIN_ENGLISH_BRIEF.md
"""
from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class Demo:
    demo_id: str
    title: str
    json_path: Path


def default_demos(root: Path) -> list[Demo]:
    """Keep in sync with scripts/export_bundle_action_sheet.py default_demos()."""
    base = root / "docs" / "sample_reports"
    return [
        Demo(
            "01_baseline",
            "Baseline — permissive policy, no injected config risk",
            base / "live_hub_tiny_bert_bundle_report.json",
        ),
        Demo(
            "02_demo_config_risk",
            "Same snapshot — demo tokenizer_config (trust_remote_code)",
            base / "live_hub_tiny_bert_bundle_report_with_demo_risk.json",
        ),
        Demo(
            "03_strict_safetensors_only",
            "Same snapshot — safetensors-only policy (reject .bin/.onnx/.h5)",
            base / "live_hub_tiny_bert_bundle_report_strict_safetensors_policy.json",
        ),
    ]


def _hub_label(data: dict[str, Any]) -> str:
    prov = data.get("provenance") or {}
    hub = prov.get("hub") or {}
    rid = str(hub.get("repo_id") or "").strip()
    rev = str(hub.get("revision") or "").strip()
    if rid and rev:
        return f"{rid} @ {rev}"
    if rid:
        return rid
    return "the Hugging Face test snapshot referenced in the bundle JSON"


def _exit_story(code: Any) -> tuple[str, str]:
    """Return (headline, what_to_do) in plain language."""
    try:
        c = int(code)
    except (TypeError, ValueError):
        return ("The scan finished with an unclear overall code.", "Ask engineering to re-run the scan and attach logs.")
    if c == 0:
        return (
            "This automated static gate did not raise a stop signal on the files we checked.",
            "You may treat this as okay for this specific check only. It does not mean the product is “safe” overall — ask your team about real-world risks (data leaks, prompt abuse, wrong model version, etc.).",
        )
    if c == 1:
        return (
            "This snapshot would fail a typical release gate until someone fixes the issue or formally accepts the risk.",
            "Do not ship to customers on this signal alone. Pick an owner (security + ML), decide fix vs waive, and record the decision.",
        )
    if c == 2:
        return (
            "A **tooling** problem happened (for example a missing scanner program or a timeout).",
            "Fix the pipeline first. This result is **not** a clean “pass” and **not** a model-malware verdict.",
        )
    if c == 4:
        return (
            "The scan was called with a **usage error** (wrong flags or paths).",
            "Ask whoever runs CI to fix the command; rerun afterward.",
        )
    return ("The scan needs human follow-up.", "Ask engineering to interpret the exit code using the technical bundle JSON.")


def _plain_config_message(msg: str) -> str:
    m = msg.strip()
    low = m.lower()
    if "trust_remote_code" in low and "hub" in low:
        return (
            "A tokenizer/loader setting is on that can let **supplier-provided code run when the model loads** "
            "(same risk family as running an installer you did not separately vet)."
        )
    if "use_auth_token" in low:
        return (
            "The config mentions using an access token. Treat this as a **secrets hygiene** check — "
            "make sure no live tokens are pasted into public repos or shared bundles."
        )
    if "use_fast_tokenizer" in low:
        return (
            "The config prefers a legacy “fast tokenizer” path. Usually an engineering/reproducibility topic, "
            "not an automatic emergency by itself."
        )
    if "auto_map" in low:
        return (
            "The config maps model pieces to **custom class names**. That can hide surprising code paths — "
            "your team should confirm where those classes come from."
        )
    if "use_safetensors" in low and "false" in low:
        return (
            "The config explicitly turns off the safer weights format preference in this file. "
            "Ask whether your org still accepts older weight formats in production."
        )
    if "invalid json" in low:
        return "At least one JSON config file does not parse — treat this as a broken build until fixed."
    return m


def _config_plain_lines(cfg: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for f in cfg[:5]:
        if not isinstance(f, dict):
            continue
        msg = str(f.get("message") or "").strip()
        if msg:
            lines.append(f"- {_plain_config_message(msg)}")
    if len(cfg) > 5:
        lines.append(f"- _(Plus {len(cfg) - 5} more rows in the technical report.)_")
    return lines


def _policy_hits(data: dict[str, Any]) -> list[str]:
    out: list[str] = []
    for fs in data.get("file_scans") or []:
        if not isinstance(fs, dict):
            continue
        rel = str(fs.get("relpath") or "")
        rep = fs.get("report") if isinstance(fs.get("report"), dict) else {}
        findings = rep.get("findings") if isinstance(rep, dict) else []
        if not isinstance(findings, list):
            continue
        for g in findings:
            if not isinstance(g, dict):
                continue
            rid = str(g.get("rule_id") or "")
            if rid == "policy.gate_violation" or str(g.get("driver") or "").lower() == "policy":
                title = str(g.get("title") or "Policy issue")
                detail = str(g.get("detail") or "").strip()
                tail = f" — {detail}" if detail else ""
                out.append(f"- **{rel or '(path unknown)'}:** {title}{tail}")
    return out


def build_markdown(demos: list[Demo]) -> str:
    lines: list[str] = [
        "# Plain-language brief (for approvers)",
        "",
        "This page is **not** a replacement for legal, compliance, or security sign-off. "
        "It translates the same three **sample** bundle scans into **everyday language** so you "
        "can decide **who to pull into the room** and **what question to ask next**.",
        "",
        "> **What this is:** a **static** check of files and config in a model folder — think “airport metal detector,” "
        "not a full background investigation. It does **not** test whether the model will behave badly in chat, "
        "whether your app is secure, or whether someone poisoned weights in a clever way the scanner did not model.",
        "",
        "---",
        "",
        "## How to use this in a meeting",
        "",
        "1. Read **Your bottom line** for each scenario below.",
        "2. If it says **stop / fail**, do not debate the math — assign **security + ML** to either **fix** or **waive with a written risk note**.",
        "3. If it says **pass for this check**, still ask whether **your** production rules need more than static files (runtime monitoring, access control, etc.).",
        "",
        "---",
        "",
    ]

    for demo in demos:
        data = json.loads(demo.json_path.read_text(encoding="utf-8"))
        agg = data.get("aggregate_exit_code")
        hub = _hub_label(data)
        headline, action = _exit_story(agg)
        cfg = [x for x in (data.get("config_findings") or []) if isinstance(x, dict)]
        policy_hits = _policy_hits(data)

        lines.extend(
            [
                f"## {demo.title}",
                "",
                f"**Teaching label:** `{demo.demo_id}` · **Model source (sample):** {hub}",
                "",
                "### Your bottom line",
                "",
                f"- **{headline}**",
                f"- **What to do next:** {action}",
                "",
            ]
        )

        if cfg:
            lines.extend(
                [
                    "### What the config check noticed (plain words)",
                    "",
                    "These are **automatic hints** from JSON settings — not proof someone attacked you:",
                    "",
                    *_config_plain_lines(cfg),
                    "",
                ]
            )

        if policy_hits:
            lines.extend(
                [
                    "### What the file rules noticed",
                    "",
                    "Your **policy** for this demo rejected at least one file path or type:",
                    "",
                    *policy_hits,
                    "",
                ]
            )

        if not cfg and not policy_hits:
            lines.extend(
                [
                    "### What the checks noticed",
                    "",
                    "On this sample, the automated config hints and policy gates we show here did **not** add extra "
                    "**stop** reasons beyond the overall headline above.",
                    "",
                ]
            )

        lines.extend(
            [
                "### If you only remember one thing",
                "",
                "- Ask: **“Did we run the right policy for how we sell this product?”**",
                "- Ask: **“Who owns the waiver if we ship anyway?”**",
                "",
                "---",
                "",
            ]
        )

    lines.extend(
        [
            "## Where the technical detail lives",
            "",
            "- **Spreadsheet + tables:** [`UNIFIED_ACTION_SHEET.csv`](UNIFIED_ACTION_SHEET.csv), [`SCAN_BRIEFING.html`](SCAN_BRIEFING.html), [`BLAST_RADIUS_LEADERSHIP.md`](BLAST_RADIUS_LEADERSHIP.md) — for engineers and auditors.",
            "- **Raw machine output:** the `docs/sample_reports/*.json` bundle files — for forensics and CI.",
            "",
            "_Regenerate this plain brief:_ `python3 scripts/export_plain_english_brief.py` or `make plain-english-brief`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root (default: parent of scripts/)",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output Markdown (default: docs/sample_reports/actionable/PLAIN_ENGLISH_BRIEF.md)",
    )
    args = ap.parse_args()
    root = args.repo_root.resolve()
    out = (args.out or (root / "docs/sample_reports/actionable/PLAIN_ENGLISH_BRIEF.md")).resolve()

    demos = default_demos(root)
    for d in demos:
        if not d.json_path.is_file():
            print(f"ERROR: missing {d.json_path}", file=sys.stderr)
            return 2

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_markdown(demos), encoding="utf-8", newline="\n")
    print(json.dumps({"plain_english_md": str(out)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
